image:
- Visual Studio 2017

environment:
  matrix:
  - Configuration: Release
    Platform: Win32

  - Configuration: Release
    Platform: x64

build_script:
  - msbuild src\libretro

artifacts:
  - path: '**\*libretro.dll'